-- Generated from generator/demo_specs/aws-thailand-food-precision-farming.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-food-precision-farming
-- This is the schema that is actually deployed for THAILAND_FOOD_PRECISION_FARMING.

-- Alerts fire on the bottom tail of Yield Forecast
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_YIELD_FORECAST) AS T
  FROM RAW.SENSOR_READINGS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_YIELD_FORECAST <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_YIELD_FORECAST), 2) AS AVG_YIELD_FORECAST,
  ROUND(AVG(f.KPI_PEST_RISK_ZONES), 2) AS AVG_PEST_RISK_ZONES,
  ROUND(AVG(f.KPI_SOIL_MOISTURE_AVG), 2) AS AVG_SOIL_MOISTURE,
  ROUND(AVG(f.KPI_FERTILIZER_EFFICIENCY), 2) AS AVG_FERTILIZER_EFFICIENCY,
  ROUND(AVG(f.KPI_DAYS_TO_HARVEST), 2) AS AVG_DAYS_TO_HARVEST
FROM RAW.SENSOR_READINGS f
JOIN RAW.THAI_AGRICULTURE e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_YIELD_FORECAST), 2) AS AVG_YIELD_FORECAST,
  ROUND(AVG(f.KPI_PEST_RISK_ZONES), 2) AS AVG_PEST_RISK_ZONES,
  ROUND(AVG(f.KPI_SOIL_MOISTURE_AVG), 2) AS AVG_SOIL_MOISTURE,
  ROUND(AVG(f.KPI_FERTILIZER_EFFICIENCY), 2) AS AVG_FERTILIZER_EFFICIENCY,
  ROUND(AVG(f.KPI_DAYS_TO_HARVEST), 2) AS AVG_DAYS_TO_HARVEST
FROM RAW.SENSOR_READINGS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_YIELD_FORECAST) AS KPI_YIELD_FORECAST, AVG(KPI_PEST_RISK_ZONES) AS KPI_PEST_RISK_ZONES, AVG(KPI_SOIL_MOISTURE_AVG) AS KPI_SOIL_MOISTURE_AVG, AVG(KPI_FERTILIZER_EFFICIENCY) AS KPI_FERTILIZER_EFFICIENCY, AVG(KPI_DAYS_TO_HARVEST) AS KPI_DAYS_TO_HARVEST FROM RAW.SENSOR_READINGS),
     en AS (SELECT SUM(KPI_WATER_STRESS_ALERTS) AS KPI_WATER_STRESS_ALERTS, SUM(KPI_MONITORED_FARMS) AS KPI_MONITORED_FARMS FROM RAW.THAI_AGRICULTURE)
  SELECT 1 AS SORT_ORDER, 'Yield Forecast' AS TITLE, KPI_YIELD_FORECAST AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_YIELD_FORECAST), 1) AS DECIMAL(38,1))) || ' ' || 'T/rai' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Water Stress Alerts' AS TITLE, KPI_WATER_STRESS_ALERTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_WATER_STRESS_ALERTS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Pest Risk Zones' AS TITLE, KPI_PEST_RISK_ZONES AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PEST_RISK_ZONES)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Monitored Farms' AS TITLE, KPI_MONITORED_FARMS AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_MONITORED_FARMS)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Soil Moisture Avg' AS TITLE, KPI_SOIL_MOISTURE_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SOIL_MOISTURE_AVG)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Fertilizer Efficiency' AS TITLE, KPI_FERTILIZER_EFFICIENCY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FERTILIZER_EFFICIENCY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Days to Harvest' AS TITLE, KPI_DAYS_TO_HARVEST AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DAYS_TO_HARVEST)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
