-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Precision Farming & Crop Analytics
-- ============================================================================
USE DATABASE PRECISION_FARMING;
USE SCHEMA ML;

-- ML.FORECAST: YIELD_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.YIELD_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.YIELD_TIMESERIES'),
  SERIES_COLNAME => 'BLOCK_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.YIELD_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.YIELD_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: CROP_STRESS_DETECTOR
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.CROP_STRESS_DETECTOR(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FIELD_HEALTH_STATUS'),
  SERIES_COLNAME => 'BLOCK_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.CROP_STRESS_DETECTOR_RESULTS AS
SELECT * FROM TABLE(ML.CROP_STRESS_DETECTOR!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FIELD_HEALTH_STATUS'), SERIES_COLNAME => 'BLOCK_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

