-- ============================================================================
-- 99_RESET.SQL — Reset Precision Farming & Crop Analytics to clean demo state
-- ============================================================================
USE DATABASE PRECISION_FARMING;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_SENSORS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_ANALYZE_IMAGERY SUSPEND;
ALTER TASK IF EXISTS APP.TASK_UPDATE_FORECASTS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.FIELD_HEALTH_STATUS REFRESH;
ALTER DYNAMIC TABLE CURATED.YIELD_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.IRRIGATION_RECOMMENDATIONS REFRESH;
ALTER DYNAMIC TABLE CURATED.PEST_DISEASE_ALERTS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM PRECISION_FARMING.RAW.SENSOR_READINGS → 1500000
-- SELECT COUNT(*) FROM PRECISION_FARMING.RAW.CROP_IMAGERY → 15000
-- SELECT COUNT(*) FROM PRECISION_FARMING.CURATED.FIELD_HEALTH_STATUS WHERE STRESS_LEVEL = 'HIGH' → >500

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_UPDATE_FORECASTS RESUME;
ALTER TASK IF EXISTS APP.TASK_ANALYZE_IMAGERY RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_SENSORS RESUME;
